# Site settings
title: Github Page - s4mu51
description: Github Page - s4mu51
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

# User settings
username: s4mu51
#user_description: 
user_title: Pentester - Cybersecurity Analyst - Bug Hunter
#email: anon@anon.com
#twitter_username: 
linkedin_username: https://www.linkedin.com/in/samuelarguellesforonda/
github_username:  https://github.com/s4mu51
htb_username:  https://app.hackthebox.com/profile/286949
thm_username:  https://tryhackme.com/p/s4mu51
yogosha_username:  https://app.yogosha.com/r/s4mu51
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
